DEFAULT  : U4.EXE

TASMOPT  = /M9 /ML /ZI /p /i.\COM /i.\EXE
TLINKOPT = /3 /li /ma /v
MAKE_TMP = $(TEMP)
VPATH    = .;.\COM;.\EXE

.SUFFIXES: .EXE .OBJ .ASM

.ASM.OBJ:
	TASM $(TASMOPT) $< ;

# MAKE builds the executable ready for debugging

MEM.OBJ : MEM.ASM COMPILER.H STDIO.H
	TASM.EXE $(TASMOPT) MEM.ASM;

STDIO.OBJ : STDIO.ASM COMPILER.H FIND.H
	TASM.EXE $(TASMOPT) STDIO.ASM;

FIND.OBJ : FIND.ASM COMPILER.H
	TASM.EXE $(TASMOPT) FIND.ASM;

INIT.OBJ : COMPILER.H VERSION.H MEM.H FIND.H STDIO.H INIT.ASM
	TASM.EXE $(TASMOPT) INIT.ASM;

U4.OBJ : $(MainSrc) COM\$(COMSrc) EXE\$(EXESrc)
	TASM.EXE $(TASMOPT) U4.ASM;

U4.EXE : U4.OBJ MEM.OBJ STDIO.OBJ FIND.OBJ INIT.OBJ
	TLINK.EXE U4.OBJ MEM.OBJ STDIO.OBJ FIND.OBJ INIT.OBJ $(TLINKOPT);

UNP.EXE : U4.EXE
	U4 L -RHFVO U4.EXE
	-DIET U4.EXE
	..\..\dshield\dshield.exe
#	UNP l -rhvo unp.exe
#	UNP l -rhfvo unp.exe

# MAKE CLEAN removes all unnessesary files from the directory
clean :
	-del *.BAK
	-del *.OBJ
	-del *.EXE
	-del *.COM
	-del *.MAP
	-del *.LST
	-del *.LOG
	-del COM\*.BAK
	-del EXE\*.BAK
	-del *.TR

#############################################################################

MainSrc =  U4.ASM GS.ASM GI.ASM INIT.ASM \
	   COMPILER.H MEM.H FIND.H STDIO.H STRING.H MAPMEM.ASM

COMSrc  =  CBWFP.ASM CCMPK.ASM CCPAV.ASM CDIET.ASM CEPW.ASM  CICE.ASM  \
           CNTCH.ASM CPKLT.ASM CPROT.ASM CPSWD.ASM CSCAN.ASM CSCRM.ASM \
	   CSCRN.ASM CSHRN.ASM CSLFD.ASM CC2CR.ASM CSYRN.ASM CXLCK.ASM \
	   CCRCM.ASM CCMPR.ASM CSPRT.ASM CNTBD.ASM CPPCK.ASM CPOJC.ASM \
	   CMCLK.ASM CSPCM.ASM CCRPT.ASM CUSRN.ASM CU173.ASM CELIT.ASM

EXESrc  =  EPKTN.ASM EGNRC.ASM EEXPK.ASM EPKLT.ASM ECMPK.ASM EPROT.ASM \
	   EPKEX.ASM EAINX.ASM EDIET.ASM ETINY.ASM ESAXE.ASM EOPTL.ASM \
	   EPGMP.ASM ESCRM.ASM ECPAV.ASM EPKSG.ASM ESCRN.ASM EDELT.ASM \
	   ECMPR.ASM EZIVP.ASM ESCAN.ASM EXLCK.ASM EMKS.ASM  EELIT.ASM \
	   EEPW.ASM  EWWPP.ASM EUCEX.ASM
